"""
ClassFiles Data Extraction System
==================================

Extracts data from ClassFiles and prepares it for integration into data source.

This script:
1. Reads catalog from catalog_classfiles.py
2. Extracts data from CSV/Excel files
3. Standardizes formats (dates, country codes, etc.)
4. Maps to BPM6 framework components
5. Validates against known series
6. Prepares for data source integration

Author: Claude
Date: 2025-10-06
"""

import os
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime
import json
from typing import Dict, List, Optional
import re

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
CLASSFILES = PROJECT_ROOT / "ClassFiles"
OUTPUT_DATA = PROJECT_ROOT / "Output" / "Data"
OUTPUT_ROOT = Path(os.environ.get("OUTPUT_ROOT", "outputs"))
FLOW_OF_FUNDS_PATH = OUTPUT_ROOT / "FLOW_OF_FUNDS"


class ClassFilesDataExtractor:
    """Extract and process data from ClassFiles."""

    def __init__(self):
        self.catalog_path = OUTPUT_DATA / "classfiles_catalog.json"
        self.catalog = None
        self.extracted_series = []

        # Load catalog if it exists
        if self.catalog_path.exists():
            with open(self.catalog_path, 'r') as f:
                self.catalog = json.load(f)

        # BPM6 component mapping
        self.bpm6_components = {
            'current_account': ['goods', 'services', 'primary_income', 'secondary_income', 'remittances'],
            'capital_account': ['capital_transfers', 'nonproduced_nonfinancial_assets'],
            'financial_account': {
                'direct_investment': ['equity', 'debt', 'reinvested_earnings'],
                'portfolio_investment': ['equity_securities', 'debt_securities'],
                'financial_derivatives': ['options', 'forwards', 'swaps'],
                'other_investment': ['trade_credits', 'loans', 'currency_deposits'],
                'reserve_assets': ['monetary_gold', 'sdr', 'reserve_position', 'foreign_exchange']
            }
        }

        # Country code mapping (ISO 3166-1 alpha-2 and alpha-3)
        self.country_codes = {
            'US': 'USA', 'UK': 'GBR', 'GB': 'GBR', 'DE': 'DEU', 'FR': 'FRA',
            'IT': 'ITA', 'JP': 'JPN', 'CN': 'CHN', 'CA': 'CAN', 'MX': 'MEX',
            'KR': 'KOR', 'AU': 'AUS', 'BR': 'BRA', 'IN': 'IND', 'RU': 'RUS'
        }

    def load_catalog(self) -> Dict:
        """Load the catalog generated by catalog_classfiles.py."""
        if not self.catalog_path.exists():
            raise FileNotFoundError(
                f"Catalog not found at {self.catalog_path}. "
                "Please run catalog_classfiles.py first."
            )

        with open(self.catalog_path, 'r') as f:
            self.catalog = json.load(f)

        print(f"[OK] Loaded catalog: {self.catalog['total_files']} files")
        return self.catalog

    def extract_all_data_files(self):
        """Extract data from all identified data files in catalog."""
        if not self.catalog:
            self.load_catalog()

        data_files = [f for f in self.catalog['files'] if f['is_data']]

        print(f"\n[PROCESSING] {len(data_files)} data files")
        print("=" * 80)

        for file_info in data_files:
            try:
                self._extract_single_file(file_info)
            except Exception as e:
                print(f"[ERROR] Failed to extract {file_info['filename']}: {e}")

        # Generate summary
        self._generate_extraction_report()

    def _extract_single_file(self, file_info: Dict):
        """Extract data from a single file."""
        file_path = Path(file_info['absolute_path'])

        print(f"\n[EXTRACTING] {file_info['filename']}")

        # Determine file type and read accordingly
        if file_info['extension'] == '.csv':
            df = self._read_csv(file_path)
        elif file_info['extension'] in ['.xlsx', '.xls']:
            df = self._read_excel(file_path)
        else:
            print(f"[SKIP] Unsupported format: {file_info['extension']}")
            return None

        if df is None or df.empty:
            print(f"[SKIP] No data extracted")
            return None

        # Analyze structure
        structure = self._analyze_structure(df, file_info)

        # Categorize by BPM6 component
        bpm6_component = self._identify_bpm6_component(df, file_info)

        # Standardize format
        standardized = self._standardize_format(df, structure, bpm6_component)

        # Save to appropriate data source directory
        if standardized is not None:
            self._save_to_robin(standardized, file_info, bpm6_component)

        return standardized

    def _read_csv(self, file_path: Path) -> Optional[pd.DataFrame]:
        """Read CSV file with error handling."""
        try:
            # Try UTF-8 first
            df = pd.read_csv(file_path, encoding='utf-8')
            print(f"  Shape: {df.shape}")
            return df
        except UnicodeDecodeError:
            # Try other encodings
            for encoding in ['latin-1', 'cp1252', 'iso-8859-1']:
                try:
                    df = pd.read_csv(file_path, encoding=encoding)
                    print(f"  Shape: {df.shape} (encoding: {encoding})")
                    return df
                except:
                    continue
        except Exception as e:
            print(f"  [ERROR] {e}")
            return None

    def _read_excel(self, file_path: Path) -> Optional[pd.DataFrame]:
        """Read Excel file with error handling."""
        try:
            # Read first sheet by default
            df = pd.read_excel(file_path, sheet_name=0)
            print(f"  Shape: {df.shape}")
            return df
        except Exception as e:
            print(f"  [ERROR] {e}")
            return None

    def _analyze_structure(self, df: pd.DataFrame, file_info: Dict) -> Dict:
        """Analyze dataframe structure to determine format."""
        structure = {
            'rows': len(df),
            'columns': len(df.columns),
            'column_names': list(df.columns),
            'has_date': False,
            'date_column': None,
            'has_country': False,
            'country_column': None,
            'value_columns': [],
            'format': 'unknown'
        }

        # Check for date columns
        for col in df.columns:
            col_lower = str(col).lower()
            if any(date_term in col_lower for date_term in ['date', 'year', 'period', 'time']):
                structure['has_date'] = True
                structure['date_column'] = col
                break

        # Check for country columns
        for col in df.columns:
            col_lower = str(col).lower()
            if any(country_term in col_lower for country_term in ['country', 'nation', 'economy', 'iso', 'code']):
                structure['has_country'] = True
                structure['country_column'] = col
                break

        # Identify value columns (numeric)
        for col in df.columns:
            if pd.api.types.is_numeric_dtype(df[col]):
                structure['value_columns'].append(col)

        # Determine format
        if structure['has_date'] and structure['has_country'] and structure['value_columns']:
            structure['format'] = 'panel'  # Country-time panel
        elif structure['has_date'] and structure['value_columns']:
            structure['format'] = 'timeseries'  # Time series
        elif structure['has_country'] and structure['value_columns']:
            structure['format'] = 'cross_section'  # Cross-sectional
        else:
            structure['format'] = 'unknown'

        print(f"  Format: {structure['format']}")
        if structure['date_column']:
            print(f"  Date column: {structure['date_column']}")
        if structure['country_column']:
            print(f"  Country column: {structure['country_column']}")
        print(f"  Value columns: {len(structure['value_columns'])}")

        return structure

    def _identify_bpm6_component(self, df: pd.DataFrame, file_info: Dict) -> str:
        """Identify which BPM6 component this data belongs to."""
        # Check filename and category
        filename_lower = file_info['filename'].lower()
        category = file_info['category'].lower()

        # Direct mappings
        if 'fdi' in filename_lower or 'direct investment' in filename_lower:
            return 'financial_account_fdi'
        elif 'portfolio' in filename_lower:
            return 'financial_account_portfolio'
        elif 'remittance' in filename_lower:
            return 'current_account_remittances'
        elif 'reserve' in filename_lower:
            return 'financial_account_reserves'
        elif 'banking' in filename_lower or 'bis' in filename_lower:
            return 'financial_account_other_investment'
        elif 'oda' in filename_lower or 'aid' in filename_lower:
            return 'current_account_transfers'
        elif 'trade' in filename_lower or 'goods' in filename_lower:
            return 'current_account_goods'
        elif 'services' in filename_lower:
            return 'current_account_services'

        # Check category
        if 'capital flows' in category:
            return 'financial_account'
        elif 'flow of funds' in category:
            return 'flow_of_funds'
        elif 'remittance' in category:
            return 'current_account_remittances'

        return 'unclassified'

    def _standardize_format(self, df: pd.DataFrame, structure: Dict, component: str) -> Optional[pd.DataFrame]:
        """Standardize data format for data source integration."""
        if structure['format'] == 'unknown':
            return None

        standardized = df.copy()

        # Standardize date column
        if structure['has_date'] and structure['date_column']:
            try:
                standardized['date'] = pd.to_datetime(standardized[structure['date_column']])
            except:
                # If date parsing fails, try year
                try:
                    standardized['year'] = pd.to_numeric(standardized[structure['date_column']])
                except:
                    pass

        # Standardize country codes
        if structure['has_country'] and structure['country_column']:
            standardized['country_code'] = standardized[structure['country_column']].apply(
                self._standardize_country_code
            )

        # Add metadata
        standardized['bpm6_component'] = component
        standardized['extracted_date'] = datetime.now().strftime('%Y-%m-%d')

        return standardized

    def _standardize_country_code(self, code: str) -> str:
        """Convert country code to ISO 3166-1 alpha-3."""
        if pd.isna(code):
            return None

        code = str(code).strip().upper()

        # Check if already alpha-3
        if len(code) == 3:
            return code

        # Convert alpha-2 to alpha-3
        if len(code) == 2:
            return self.country_codes.get(code, code)

        return code

    def _save_to_robin(self, df: pd.DataFrame, file_info: Dict, component: str):
        """Save extracted data to appropriate data source directory."""
        # Determine target directory based on component
        if component.startswith('financial_account_fdi'):
            target_dir = FLOW_OF_FUNDS_PATH / "OECD_FDI_Bilateral"
        elif component.startswith('financial_account_portfolio'):
            target_dir = FLOW_OF_FUNDS_PATH / "IMF_CPIS"
        elif component.startswith('current_account_remittances'):
            target_dir = FLOW_OF_FUNDS_PATH / "World_Bank_Remittances"
        elif component.startswith('financial_account_other_investment'):
            target_dir = FLOW_OF_FUNDS_PATH / "BIS_Banking_Statistics"
        elif component.startswith('current_account_transfers'):
            target_dir = FLOW_OF_FUNDS_PATH / "OECD_DAC_ODA"
        else:
            target_dir = FLOW_OF_FUNDS_PATH / "Other"

        target_dir.mkdir(parents=True, exist_ok=True)

        # Generate filename
        original_stem = Path(file_info['filename']).stem
        output_filename = f"{original_stem}_extracted.csv"
        output_path = target_dir / output_filename

        # Save
        df.to_csv(output_path, index=False)
        print(f"  [SAVED] {output_path.relative_to(PROJECT_ROOT)}")

        # Track extraction
        self.extracted_series.append({
            'original_file': file_info['filename'],
            'output_file': str(output_path.relative_to(PROJECT_ROOT)),
            'component': component,
            'rows': len(df),
            'columns': len(df.columns)
        })

    def _generate_extraction_report(self):
        """Generate report of extraction process."""
        report_path = OUTPUT_DATA / "EXTRACTION_REPORT.md"

        report = []
        report.append("# ClassFiles Data Extraction Report")
        report.append(f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"\nTotal series extracted: {len(self.extracted_series)}")
        report.append("\n" + "=" * 80)

        report.append("\n## Extracted Series\n")
        for series in self.extracted_series:
            report.append(f"**{series['original_file']}**")
            report.append(f"- Component: {series['component']}")
            report.append(f"- Output: `{series['output_file']}`")
            report.append(f"- Dimensions: {series['rows']:,} rows × {series['columns']} columns")
            report.append("")

        # Component summary
        components = {}
        for series in self.extracted_series:
            comp = series['component']
            if comp not in components:
                components[comp] = 0
            components[comp] += 1

        report.append("\n## By BPM6 Component\n")
        for comp, count in sorted(components.items()):
            report.append(f"- **{comp}**: {count} series")

        report.append("\n## Next Steps\n")
        report.append("1. Review extracted data quality")
        report.append("2. Validate against known series structures")
        report.append("3. Cross-reference with methodology documents")
        report.append("4. Integrate into main data source")
        report.append("5. Update PROJECT_INDEX.md with new data availability")

        with open(report_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report))

        print(f"\n[OK] Extraction report saved to: {report_path}")


def main():
    """Main execution function."""
    print("\n" + "=" * 80)
    print("ClassFiles Data Extraction System")
    print("=" * 80)

    extractor = ClassFilesDataExtractor()

    try:
        extractor.load_catalog()
        extractor.extract_all_data_files()

        print("\n" + "=" * 80)
        print("Extraction Complete!")
        print("=" * 80)
        print(f"Series extracted: {len(extractor.extracted_series)}")
        print("\nCheck $DATA_ROOT/FLOW_OF_FUNDS/ for extracted data")

    except FileNotFoundError as e:
        print(f"\n[ERROR] {e}")
        print("\nPlease run catalog_classfiles.py first to generate the catalog.")


if __name__ == "__main__":
    main()
